services:
  snippetbox:
    container_name: snippetbox
    image: cosmtrek/air
    working_dir: /snippetbox
    ports:
      - "4001:4000"
    restart: unless-stopped
    volumes:
      - ./snippetbox/:/snippetbox/
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    container_name: mysql
    image: mysql:9
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: snippetbox
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 2s
      timeout: 5s
      retries: 3

  greenlight:
    container_name: greenlight
    image: cosmtrek/air
    working_dir: /greenlight
    ports:
      - "4000:4000"
    restart: unless-stopped
    environment:
      GREENLIGHT_DB_DSN: "postgres://greenlight:pa55word@postgres/greenlight?sslmode=disable"
    volumes:
      - ./greenlight/:/greenlight/
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: greenlight
      POSTGRES_PASSWORD: pa55word
      POSTGRES_DB: greenlight
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "greenlight", "-d", "greenlight"]
      interval: 2s
      timeout: 5s
      retries: 3

volumes:
  mysql-data:
  postgres-data:
