services:
  snippetbox:
    container_name: snippetbox
    image: cosmtrek/air
    working_dir: /snippetbox
    ports:
      - "4001:4000"
    restart: unless-stopped
    volumes:
      - ./snippetbox/:/snippetbox/
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    container_name: mysql
    image: mysql:9
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: snippetbox
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 2s
      timeout: 5s
      retries: 3

  greenlight:
    container_name: greenlight
    image: cosmtrek/air
    working_dir: /greenlight
    ports:
      - "4000:4000"
    restart: unless-stopped
    volumes:
      - ./greenlight/:/greenlight/
volumes:
  mysql-data:
